inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
